#ifndef SETTINGS_H
#define SETTINGS_H

#ifndef DEBUG
#define DEBUG 0
#endif

#ifndef RESPONSE_DELAY_TIME_IN_MILLISECONDS
#define RESPONSE_DELAY_TIME_IN_MILLISECONDS 1000
#endif

#ifndef SHUTDOWN_COOLDOWN_IN_MILLISECONDS
#define SHUTDOWN_COOLDOWN_IN_MILLISECONDS 3000
#endif

#endif
